import "../../justfile"

_default:
	@just --list

# compile Project2 with all files
compile-java:
	javac Project2.java Complex.java Polynomial.java Secant.java -d out/

# run Project2 to test everything
run class="Project2": compile-java
	java -enableassertions -classpath out {{class}}

_pre-build: run

# build and rename main.pdf to Fractal.pdf
rename: build
	mv main.pdf Fractal.pdf
