import "../../justfile"

_default:
	@just --list

# compile Project1 with all files
compile-java:
	javac Project1.java Circle.java Point.java -d out/

# run Project1 to test everything
run: compile-java
	java -enableassertions -classpath out Project1

# remove all build artifacts
clean:
	rm -rfv out/
