export TEXMFHOME := justfile_directory() + "/texmf"

_default:
	@just --list

# build the assignment in the current directory (assuming main.tex)
build:
	cd "{{invocation_directory()}}" && lualatex -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape -recorder --jobname="main" "main.tex"

# remove all build artifacts and clean things up
clean:
	cd "{{invocation_directory()}}" && latexmk -c -C
	texhash
