import "../../justfile"

_default:
	@just --list

# compile Project3 with all files
compile-java:
	javac Project3.java Matrix.java MatrixException.java GeneralMatrix.java TriMatrix.java -d out/

# run Project3
run class="Project3": compile-java
	java -enableassertions -classpath out {{class}}

# build VarGraph.pdf using the generated data
build:
	just run Project3 | tee variance.data
	nix-shell -p octave -p ghostscript --run "octave --norc create_var_graph.m"

# build and rename PDF
rename: build

# remove all build artifacts
clean:
	rm -rfv out/ variance.data
