import "../../../justfile"

set allow-duplicate-recipes # Needed for _default and _pre-build

_default:
	@just --list

[group("pdf")]
_pre-build:
	nix-shell code/shell.nix --run ./code/plot_torus.py
	@just _build
