import "../../justfile"

set allow-duplicate-recipes := true

alias j := jupyter

_default:
    @just --list

# run a JupyterLab server
[group("python")]
[no-cd]
jupyter:
    python -m jupyter lab

# run the notebook from scratch
[group("python")]
[no-cd]
run:
    python -m jupyter execute *.ipynb --inplace

_pre-build: run
