name: Build every assignment

on: push

jobs:
  build-assignments:
    runs-on: ubuntu-latest

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: doctordalek1963
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Create TMPDIR
        run: |
          mkdir -p /home/runner/work/tmp
          echo "TMPDIR=/home/runner/work/tmp" >> $GITHUB_ENV

      - name: Install nix-direnv
        run: |
          mkdir -p "${XDG_CONFIG_HOME}/direnv/lib"
          cp "$(nix-build --expr "(import <nixpkgs> {}).nix-direnv")"/share/nix-direnv/direnvrc "${XDG_CONFIG_HOME}/direnv/lib/nix-direnv.sh"

      - name: Setup build cache
        uses: actions/cache@v4
        with:
          key: build-cache-${{ github.sha }}
          restore-keys: |
            build-cache-
          path: build-cache.pickle

      - name: Build every assignment
        run: nix develop .#ci --command just ci-build-changed
