name: Build every assignment

on: push

jobs:
  build-assignments:
    runs-on: ubuntu-latest

    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - uses: DeterminateSystems/flakehub-cache-action@v1

      - name: Create TMPDIR
        run: |
          mkdir -p /home/runner/work/tmp
          echo "TMPDIR=/home/runner/work/tmp" >> $GITHUB_ENV

      - name: Remove nix-direnv
        run: nix-shell -p fd -p sd --run "fd -H .envrc -X sd -F nix_direnv_manual_reload ''"

      - name: Build every assignment
        run: nix-shell --run "just ci-build-all"
