import "../../../justfile"

set allow-duplicate-recipes # Needed for _default and _pre-build

_default:
	@just --list

_pre-build:
	nix-shell code/shell.nix --run ./code/generate_plots.py
	@just _build
